//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakip.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokMvcEntities : DbContext
    {
        public StokMvcEntities()
            : base("name=StokMvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_kategoriler> tbl_kategoriler { get; set; }
        public virtual DbSet<tbl_musteriler> tbl_musteriler { get; set; }
        public virtual DbSet<tbl_Satislar> tbl_Satislar { get; set; }
        public virtual DbSet<tbl_Urunler> tbl_Urunler { get; set; }
    }
}
