//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Satislar
    {
        public int Id { get; set; }
        public Nullable<int> SatilanUrun { get; set; }
        public Nullable<int> UrunMusterisi { get; set; }
        public Nullable<byte> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual tbl_musteriler tbl_musteriler { get; set; }
        public virtual tbl_Urunler tbl_Urunler { get; set; }
    }
}
